(PE-15999) Collect logs from journalctl
This patch adds journalctl output for each PE service to the list of log files
collected by the support script.

diff --git a/files/puppet-enterprise-support b/files/puppet-enterprise-support
--- a/files/puppet-enterprise-support
+++ b/files/puppet-enterprise-support
@@ -683,8 +683,55 @@ grab_env_vars() {
   run_diagnostic "env" "system/env.txt"
 }
 
+
+# Copy PE service logs to support script output.
+#
+# Captures /var/log/puppetlabs along with journalctl output
+# for each PE service.
+#
+# Global Variables Used:
+#   DROP
+#
+# Arguments:
+#   None
+#
+# Returns:
+#   None
 pe_logs() {
-  cp -LpR /var/log/puppetlabs/* "${DROP}/logs"
+  local pe_services
+  local agent_services
+
+  cp -LpR /var/log/puppetlabs/* "${DROP?}/logs"
+
+  pe_services=(
+    'nginx'
+    'puppetserver'
+    'puppetdb'
+    'activemq'
+    'console-services'
+    'orchestration-services'
+    'postgresql'
+  )
+
+  agent_services=(
+    'puppet'
+    'pxp-agent'
+    'mcollective'
+  )
+
+  if cmd journalctl; then
+    # journalctl always exits with code 1 if a unit hasn't logged any output.
+    # Therefore, we mask the exit code with `|| true` so that tests pass.
+    for s in "${pe_services[@]}"; do
+      if [[ -d "${DROP}/logs/${s}" ]]; then
+        run_diagnostic "journalctl --full --unit=pe-${s} || true" "logs/${s}/${s}-journalctl.log"
+      fi
+    done
+
+    for s in "${agent_services[@]}"; do
+      run_diagnostic "journalctl --full --unit=${s} || true" "logs/${s}-journalctl.log"
+    done
+  fi
 
   if [[ -d '/var/lib/peadmin/.mcollective.d' ]]; then
     mkdir -p "${DROP}/logs/peadmin"
