(PE-16085) Enable strict failures during tests
This patch enables some strict Bash settings when the BEAKER_TESTING
environment variable is set:

    set -xeuo pipefail

These settings help to surface the use of undefined variables or
commands that fail when run against a clean installation.

diff --git a/files/puppet-enterprise-support b/files/puppet-enterprise-support
--- a/files/puppet-enterprise-support
+++ b/files/puppet-enterprise-support
@@ -16,6 +16,11 @@
 # This program runs diagnostics for Puppet Enterprise. Run this file to
 # run the diagnostics and data aggregation.
 
+if [[ -n "${BEAKER_TESTING}" ]]; then
+  # Enable command tracing and strict failures during tests.
+  set -xeuo pipefail
+fi
+
 
 #===[ Global variables ]================================================
 readonly PUPPET_BIN_DIR='/opt/puppetlabs/puppet/bin'
